### ISSUE TITLE
Suggestion: International support

### ISSUE THREAD

**Issue by Martinspire** [doppler/weatherflow-node#1]
I'm still waiting for my Tempest but was looking around for some screen solutions.
By looking at the readme, I see that the locations supported for the config, only seem to be US states/cities. Which would be a shame for us international users. Any chance it will get updated for this? Or am I worried for nothing?

**Comment by doppler** [comment]
The location is only relevant for the winds aloft data, which I imagine are not of interest to most people who are not pilots or air sports participants. You could simply comment out the corresponding JS and HTML parts in the dashboard code.
