### ISSUE TITLE
Unable to compose influxdb

### ISSUE THREAD

**Issue by desmando** [doppler/weatherflow-node#4]
I'm following your steps on a RPi4 (doublechecked on Ubuntu 20.04 vm).
Got an error when trying to run docker-compose up influxdb

`mike@weatherflow:~/weatherflow-node$ docker-compose up influxdb

weatherflow-node_influxdb_1 is up-to-date

Attaching to weatherflow-node_influxdb_1

influxdb_1    | standard_init_linux.go:228: exec user process caused: exec format error

influxdb_1    | standard_init_linux.go:228: exec user process caused: exec format error

influxdb_1    | standard_init_linux.go:228: exec user process caused: exec format error

influxdb_1    | standard_init_linux.go:228: exec user process caused: exec format error

weatherflow-node_influxdb_1 exited with code 1

mike@weatherflow:~/weatherflow-node$
`

**Comment by doppler** [comment]
To run it on Ubuntu, you'd have to comment out line 6 and uncomment line 7 in docker-compose.yml, i.e. use the quay.io/influxdb image instead of the one I built for ARM. Make sure you're using a 64 bit build of Raspi OS, as the InfluxDB image I built was for ARM64.

**Comment by desmando** [comment]
Any thoughts why it doesn't work on raspian?

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by doppler** [comment]
> Any thoughts why it doesn't work on raspian? 

I only got everything to work together when I used a 64-bit build of Raspberry Pi OS. Try one of these:

https://downloads.raspberrypi.org/raspios_arm64/images/

**Comment by desmando** [comment]
Will do

Sent via the Samsung Galaxy S10+, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by desmando** [comment]
Now that I actually followed your instructions it has worked to the point where I can open the dashboard. Problem now is that none of the tempest panels actually have data.
![tempest](https://user-images.githubusercontent.com/6901750/120687929-5d36bf80-c457-11eb-91c8-feca11aff57e.PNG)

**Comment by desmando** [comment]
I missed one step. I'm sorry to have bothered you. Everything is working perfectly now.
